version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./api  
    ports:
      - "8800:8800"  
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_DATABASE=blog
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./client  
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    container_name: db
    image: mysql:latest  
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=blog
